services:
  auth_service:
    env_file:
      - .env
    build:  ./auth_service
    ports:
      - "8001:8000"
    environment:
      MONGO_SERVICE_URL: ${MONGO_SERVICE_URL}
    depends_on: [mongo_service]

  mongo_service:
    env_file:
      - .env
    build: ./mongo_service
    ports:
      - "8002:8000"


